site_name: AlgoTech
site_url: https://algotech.in
copyright: Copyright &copy; algotech.in 2024

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - admonition
  - tables
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: false

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://www.googletagmanager.com/gtag/js?id=G-XYZX98MFG8

plugins:
  - blog:
      post_date_format: full
      post_excerpt: required
  - glightbox
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

theme:
  name: material
  language: en
#  favicon: images/favicon.svg
#  logo: images/favicon.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
      primary: teal
      accent: teal

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
      primary: teal
      accent: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: teal

  features:
    - navigation.indexes
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.suggest

nav:
  - Blog:
    - blog/index.md
  - Home: index.md
  - Leetcode:
      - Easy:
         - Disappeared Numbers in Array: leetcode-easy/find-all-numbers-disappeared-in-an-array.md
         - First Bad Version: leetcode-easy/first-bad-version.md
         - Binary Tree Paths: leetcode-easy/binary-tree-paths.md
         - N-ary Tree Preorder Traversal: leetcode-easy/n-ary-tree-preorder-traversal.md
         - Array Partition: leetcode-easy/array-partition.md
         - Ransom Note: leetcode-easy/ransom-note.md
         - Stack using Queues: leetcode-easy/implement-stack-using-queues.md
         - Add Number Strings: leetcode-easy/add-number-strings.md
         - Number of Segments in a String: leetcode-easy/number-of-segments-in-a-string.md
         - Assign Cookies: leetcode-easy/assign-cookies.md
